apiVersion: apps/v1
kind: Deployment
metadata:
  name: webform-nginx
  namespace: new
  labels:
    app: webform-nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: webform-nginx
  template:
    metadata:
      labels:
        app: webform-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: {{ .Values.nginx.port }}
