apiVersion: apps/v1
kind: Deployment
metadata:
  name: webform-php
  namespace: new
  labels:
    app: webform-php
spec:
  replicas: {{ .Values.php.replicas }}
  selector:
    matchLabels:
      app: webform-php
  template:
    metadata:
      labels:
        app: webform-php
    spec:
      containers:
        - name: php
          image: "{{ .Values.php.image }}:{{ .Values.buildTag }}"
          ports:
            - containerPort: {{ .Values.php.port }}
