apiVersion: v1
kind: Service
metadata:
  name: webform-nginx
  namespace: new
spec:
  selector:
    app: webform-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.nginx.port }}
      nodePort: 30080
  type: NodePort
