replicaCount: 2

phpImage:
  repository: mhadiltt/webform-php
  tag: latest

nginxImage:
  repository: mhadiltt/webform-nginx
  tag: latest

service:
  type: NodePort
  port: 80

ingress:
  enabled: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

env:
  APP_ENV: production
