name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: PHP Syntax Check
      run: |
        find src -name "*.php" -exec php -l {} \;

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t your-registry/web-form-app:${{ github.sha }} .
    
    - name: Push Docker image
      run: |
        docker push your-registry/web-form-app:${{ github.sha }}
    
    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install web-form-app ./kubernetes/chart \
          --set image.tag=${{ github.sha }} \
          --namespace web-form-app \
          --create-namespace
